; zend_extension=xdebug.so
xdebug.mode=develop,debug
xdebug.discover_client_host=${XDEBUG_DISCOVER_CLIENT_HOST}
xdebug.client_host=host.docker.internal
xdebug.client_port=9003
xdebug.idekey = PHPSTORM
xdebug.start_with_request=trigger
xdebug.collect_return=0
xdebug.collect_assignments=0
